
import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect,useState } from "react";
import { Layout } from "@/components/Layout"; import { ProductCard } from "@/components/ProductCard";
import { useLang } from "@/lib/i18n"; import { useStore } from "@/lib/store"; import type { Product } from "@/lib/mock-data";
import { Sparkles,Camera,Mic,ShieldCheck,Zap } from "lucide-react";
type Category={id:string;name:string;nameBn:string;emoji:string};
const API=import.meta.env.VITE_API_URL??"http://localhost:5000/api";
export const Route=createFileRoute("/")({head:()=>({meta:[{title:"HyperLocal — Compare Local & Online Sellers in One Marketplace"}]}),component:Index});
function Index(){const {lang,t}=useLang();const {viewed,wishlist}=useStore();const [categories,setCategories]=useState<Category[]>([]);const [products,setProducts]=useState<Product[]>([]);
useEffect(()=>{Promise.all([fetch(`${API}/categories`).then(r=>r.json()),fetch(`${API}/products?sort=rating`).then(r=>r.json())]).then(([c,p])=>{setCategories(c);setProducts(p.items)})},[]);
return <Layout>
<section className="overflow-hidden rounded-3xl bg-hero-gradient p-8 text-primary-foreground shadow-lift md:p-12"><span className="inline-flex items-center gap-1.5 rounded-full bg-primary-foreground/15 px-3 py-1 text-xs font-semibold"><Sparkles className="size-3.5"/> AI-powered · Bangla & English</span><h1 className="mt-4 max-w-2xl font-display text-3xl font-extrabold leading-tight md:text-5xl">{lang==="bn"?"পাড়ার দোকান আর অনলাইন সেলার — এক জায়গায়":"Every shop near you, and every online seller, in one place"}</h1><p className="mt-3 max-w-xl text-sm opacity-90 md:text-base">{t("tagline")}</p><div className="mt-6 flex flex-wrap gap-2"><Link to="/search" className="rounded-xl bg-accent-gradient px-5 py-2.5 text-sm font-bold text-accent-foreground">Start shopping</Link><Link to="/seller" className="rounded-xl border border-primary-foreground/40 px-5 py-2.5 text-sm font-semibold">Seller dashboard</Link></div><div className="mt-8 grid gap-3 sm:grid-cols-3">{[{icon:Camera,label:t("visualSearch"),sub:"Upload a photo, find the item"},{icon:Mic,label:t("voiceSearch"),sub:"Speak in Bangla or English"},{icon:ShieldCheck,label:"Fake review detection",sub:"Ratings you can trust"}].map(f=><div key={f.label} className="rounded-2xl bg-primary-foreground/10 p-4"><f.icon className="size-5"/><p className="mt-2 text-sm font-semibold">{f.label}</p><p className="text-xs opacity-80">{f.sub}</p></div>)}</div></section>
<section className="mt-8"><h2 className="font-display text-xl font-bold">{t("categories")}</h2><div className="mt-3 grid grid-cols-3 gap-3 sm:grid-cols-6">{categories.map(c=><Link key={c.id} to="/search" search={{q:"",category:c.id}} className="card-surface flex flex-col items-center gap-1 p-4 text-center transition-transform hover:-translate-y-1"><span className="text-2xl">{c.emoji}</span><span className="text-xs font-semibold">{lang==="bn"?c.nameBn:c.name}</span></Link>)}</div></section>
<section className="mt-10"><h2 className="font-display text-xl font-bold">{t("recommended")}</h2><p className="text-xs text-muted-foreground">{lang==="bn"?"আপনার ব্রাউজিং ও উইশলিস্ট থেকে":"Built from your saved and viewed products"}</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0,4).map(p=><ProductCard key={p.id} product={p}/>)}</div></section>
<section className="mt-10"><h2 className="flex items-center gap-2 font-display text-xl font-bold"><Zap className="size-5 text-accent"/>{t("trending")}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{products.filter(p=>p.tags.includes("trending")).slice(0,4).map(p=><ProductCard key={p.id} product={p}/>)}</div></section>
</Layout>}
