
import { createFileRoute } from "@tanstack/react-router";
import { useEffect,useState } from "react";
import { Layout } from "@/components/Layout"; import { ProductCard } from "@/components/ProductCard"; import { useLang,money } from "@/lib/i18n";
import { SlidersHorizontal } from "lucide-react"; import type { Product } from "@/lib/mock-data";
const API=import.meta.env.VITE_API_URL??"http://localhost:5000/api";
type SearchParams={q:string;category:string|undefined};
type Category={id:string;name:string;nameBn:string;emoji:string};
export const Route=createFileRoute("/search")({validateSearch:(s:Record<string,unknown>):SearchParams=>({q:typeof s.q==="string"?s.q:"",category:typeof s.category==="string"?s.category:undefined}),component:SearchPage});
function SearchPage(){const {q,category}=Route.useSearch();const {lang,t}=useLang();const [cat,setCat]=useState(category);const [maxPrice,setMaxPrice]=useState(10000);const [minRating,setMinRating]=useState(0);const [localOnly,setLocalOnly]=useState(false);const [sort,setSort]=useState("relevance");const [list,setList]=useState<Product[]>([]);const [categories,setCategories]=useState<Category[]>([]);
useEffect(()=>{fetch(`${API}/categories`).then(r=>r.json()).then(setCategories)},[]);
useEffect(()=>{const p=new URLSearchParams({q,sort,maxPrice:String(maxPrice),minRating:String(minRating),localOnly:String(localOnly)});if(cat)p.set("category",cat);fetch(`${API}/products?${p}`).then(r=>r.json()).then(x=>setList(x.items))},[q,cat,maxPrice,minRating,localOnly,sort]);
return <Layout><h1 className="font-display text-2xl font-bold">{q?`“${q}”`:lang==="bn"?"সব পণ্য":"All products"} <span className="text-base font-normal text-muted-foreground">· {list.length} {t("results")}</span></h1><div className="mt-4 grid gap-6 lg:grid-cols-[240px_1fr]"><aside className="card-surface h-fit space-y-5 p-4"><h2 className="flex items-center gap-2 font-display font-bold"><SlidersHorizontal className="size-4"/>{t("filters")}</h2><div><p className="mb-2 text-xs font-semibold uppercase text-muted-foreground">{t("categories")}</p><div className="flex flex-wrap gap-1.5"><button onClick={()=>setCat(undefined)} className={"rounded-full border px-2.5 py-1 text-xs "+(!cat?"border-primary bg-primary text-primary-foreground":"border-border")}>All</button>{categories.map(c=><button key={c.id} onClick={()=>setCat(c.id===cat?undefined:c.id)} className={"rounded-full border px-2.5 py-1 text-xs "+(cat===c.id?"border-primary bg-primary text-primary-foreground":"border-border")}>{c.emoji} {lang==="bn"?c.nameBn:c.name}</button>)}</div></div><div><p className="mb-1 text-xs font-semibold uppercase text-muted-foreground">Max price · {money(maxPrice,lang)}</p><input type="range" min={500} max={10000} step={100} value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))} className="w-full"/></div><div><p className="mb-1 text-xs font-semibold uppercase text-muted-foreground">Minimum rating</p><input type="range" min={0} max={5} step={0.5} value={minRating} onChange={e=>setMinRating(Number(e.target.value))} className="w-full"/></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={localOnly} onChange={e=>setLocalOnly(e.target.checked)}/>Local sellers only</label></aside><div><div className="mb-3 flex justify-end"><select value={sort} onChange={e=>setSort(e.target.value)} className="rounded-lg border bg-background px-3 py-2 text-sm"><option value="relevance">Relevance</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option><option value="rating">Highest rated</option></select></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{list.map(p=><ProductCard key={p.id} product={p}/>)}</div></div></div></Layout>}
