export const sellers = [
  { id: "s1", name: "Dhanmondi Electronics", nameBn: "ধানমন্ডি ইলেকট্রনিক্স", area: "Dhanmondi, Dhaka", rating: 4.7, isLocal: true, verified: true, since: "2019", responseTime: "~12 min" },
  { id: "s2", name: "TechHub BD Online", nameBn: "টেকহাব বিডি", area: "Nationwide", rating: 4.5, isLocal: false, verified: true, since: "2017", responseTime: "~1 hr" },
  { id: "s3", name: "Uttara Gadget Corner", nameBn: "উত্তরা গ্যাজেট কর্নার", area: "Uttara, Dhaka", rating: 4.3, isLocal: true, verified: false, since: "2021", responseTime: "~30 min" },
  { id: "s4", name: "Chattogram Fresh Mart", nameBn: "চট্টগ্রাম ফ্রেশ মার্ট", area: "Agrabad, Chattogram", rating: 4.8, isLocal: true, verified: true, since: "2020", responseTime: "~8 min" },
  { id: "s5", name: "Gulshan Fashion & Lifestyle", nameBn: "গুলশান ফ্যাশন ও লাইফস্টাইল", area: "Gulshan 2, Dhaka", rating: 4.9, isLocal: true, verified: true, since: "2018", responseTime: "~15 min" },
  { id: "s6", name: "Green Valley Organics", nameBn: "গ্রীন ভ্যালি অর্গানিকস", area: "Mirpur, Dhaka", rating: 4.8, isLocal: true, verified: true, since: "2021", responseTime: "~10 min" },
];

export const categories = [
  { id: "electronics", name: "Electronics", nameBn: "ইলেকট্রনিক্স", emoji: "📱" },
  { id: "grocery", name: "Grocery", nameBn: "মুদি", emoji: "🥬" },
  { id: "fashion", name: "Fashion", nameBn: "ফ্যাশন", emoji: "👕" },
  { id: "home", name: "Home & Living", nameBn: "গৃহসজ্জা", emoji: "🛋️" },
  { id: "beauty", name: "Beauty", nameBn: "প্রসাধনী", emoji: "💄" },
  { id: "sports", name: "Sports", nameBn: "খেলাধুলা", emoji: "🏏" },
];

export const products = [
  {
    id: "p1",
    name: "Wireless Noise-Cancelling Headphones",
    nameBn: "ওয়্যারলেস নয়েজ ক্যান্সেলিং হেডফোন",
    brand: "SoundPeak",
    category: "electronics",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
    emoji: "🎧",
    price: 6450,
    oldPrice: 8900,
    rating: 4.6,
    reviewCount: 1284,
    description: "40h battery, hybrid ANC, dual-device pairing and a foldable travel case. Tuned for podcasts and commute noise.",
    descriptionBn: "৪০ ঘণ্টা ব্যাটারি, হাইব্রিড এএনসি, দুই ডিভাইস পেয়ারিং এবং ভাঁজযোগ্য ট্রাভেল কেস।",
    specs: { Battery: "40 hours", ANC: "Hybrid, 32dB", Bluetooth: "5.3", Weight: "248 g", Warranty: "1 year local" },
    offers: [
      { sellerId: "s1", price: 6450, delivery: "Same day in Dhanmondi", stock: 7 },
      { sellerId: "s2", price: 6299, delivery: "2-3 days nationwide", stock: 45 },
      { sellerId: "s3", price: 6690, delivery: "Next day in Uttara", stock: 3 },
    ],
    reviews: [
      { id: "r1", user: "Nusrat J.", rating: 5, text: "ANC is excellent on the bus. Battery easily lasts a week of commuting.", date: "2 days ago" },
      { id: "r2", user: "Rakib H.", rating: 4, text: "Great sound, but the ear cups get warm after 3 hours.", date: "1 week ago" },
      { id: "r3", user: "user_88213", rating: 5, text: "Best product ever!!! Buy now!!! Amazing seller amazing price!!!", date: "1 week ago", suspicious: true, reason: "Generic praise, new account, 14 identical reviews posted in 6 minutes" },
      { id: "r4", user: "Tanvir A.", rating: 3, text: "Mic quality on calls is average. Music is good though.", date: "3 weeks ago" },
    ],
    aiSummary: "Buyers consistently praise the noise cancellation and 40-hour battery for daily commuting. The most common complaint is warmth after long sessions, and several reviewers note call-mic quality is only average.",
    tags: ["trending", "best-anc", "audio", "headphones"],
  },
  {
    id: "p2",
    name: "Smart Fitness Band 6",
    nameBn: "স্মার্ট ফিটনেস ব্যান্ড ৬",
    brand: "PulseFit",
    category: "electronics",
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&w=800&q=80",
    emoji: "⌚",
    price: 2890,
    oldPrice: 3500,
    rating: 4.3,
    reviewCount: 642,
    description: "AMOLED display, SpO2 and heart rate tracking, 14-day battery, 5ATM water resistance.",
    descriptionBn: "অ্যামোলেড ডিসপ্লে, SpO2 ও হার্ট রেট ট্র্যাকিং, ১৪ দিন ব্যাটারি।",
    specs: { Display: "1.56\" AMOLED", Battery: "14 days", Water: "5ATM", Sensors: "HR, SpO2, Accel", Warranty: "6 months" },
    offers: [
      { sellerId: "s2", price: 2890, delivery: "2-3 days nationwide", stock: 120 },
      { sellerId: "s3", price: 2950, delivery: "Next day in Uttara", stock: 12 },
    ],
    reviews: [
      { id: "r1", user: "Farhana K.", rating: 4, text: "Step count is accurate, sleep tracking is a bit optimistic.", date: "4 days ago" },
      { id: "r2", user: "Imran S.", rating: 5, text: "Battery really does last two weeks with notifications on.", date: "2 weeks ago" },
    ],
    aiSummary: "Reviewers highlight the genuinely long battery life and accurate step tracking. Sleep tracking accuracy is the recurring doubt.",
    tags: ["budget", "smartwatch", "fitness", "wearable"],
  },
  {
    id: "p3",
    name: "Premium Basmati Rice 5kg",
    nameBn: "প্রিমিয়াম বাসমতি চাল ৫ কেজি",
    brand: "Golden Field",
    category: "grocery",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80",
    emoji: "🍚",
    price: 890,
    oldPrice: 1050,
    rating: 4.8,
    reviewCount: 310,
    description: "Aged 12 months, extra long grain, ideal for biryani and polao.",
    descriptionBn: "১২ মাস পুরনো, অতিরিক্ত লম্বা দানা, বিরিয়ানি ও পোলাওয়ের জন্য আদর্শ।",
    specs: { Weight: "5 kg", Origin: "Dinajpur", Type: "Aged basmati", Packaging: "Sealed jute-lined" },
    offers: [
      { sellerId: "s4", price: 890, delivery: "Same day in Chattogram", stock: 60 },
      { sellerId: "s6", price: 910, delivery: "Same day in Mirpur", stock: 35 },
      { sellerId: "s1", price: 935, delivery: "Same day in Dhanmondi", stock: 22 },
    ],
    reviews: [
      { id: "r1", user: "Shirin B.", rating: 5, text: "Grains stay separate in polao. Consistent quality across three orders.", date: "5 days ago" },
      { id: "r2", user: "Kamrul I.", rating: 4, text: "Good rice, packaging arrived slightly torn.", date: "3 weeks ago" },
    ],
    aiSummary: "Nearly all reviewers describe consistent grain quality and good aroma, especially for biryani.",
    tags: ["local-favourite", "rice", "grocery", "food"],
  },
  {
    id: "p4",
    name: "Handloom Cotton Panjabi",
    nameBn: "হ্যান্ডলুম কটন পাঞ্জাবি",
    brand: "Tantu",
    category: "fashion",
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80",
    emoji: "👘",
    price: 1750,
    oldPrice: 2200,
    rating: 4.5,
    reviewCount: 188,
    description: "Handwoven cotton, breathable for summer, natural dye finish with wooden buttons.",
    descriptionBn: "হাতে বোনা সুতি, গ্রীষ্মের জন্য আরামদায়ক, প্রাকৃতিক রঙ।",
    specs: { Fabric: "100% handloom cotton", Fit: "Regular", Care: "Hand wash cold", Sizes: "S-XXL" },
    offers: [
      { sellerId: "s5", price: 1750, delivery: "Same day in Gulshan", stock: 20 },
      { sellerId: "s1", price: 1790, delivery: "Same day in Dhanmondi", stock: 15 },
      { sellerId: "s2", price: 1820, delivery: "2-3 days nationwide", stock: 40 },
    ],
    reviews: [
      { id: "r1", user: "Sabbir R.", rating: 5, text: "Fabric is genuinely handloom, very comfortable in heat.", date: "1 week ago" },
      { id: "r2", user: "Mahin C.", rating: 4, text: "Colour bled slightly on first wash, fine afterwards.", date: "1 month ago" },
    ],
    aiSummary: "Buyers value the authentic handloom feel and summer comfort. Sizing runs true to chart.",
    tags: ["local-artisan", "panjabi", "ethnic", "fashion"],
  },
  {
    id: "p5",
    name: "Ceramic Cookware Set (5 pcs)",
    nameBn: "সিরামিক কুকওয়্যার সেট (৫ পিস)",
    brand: "HomeCraft",
    category: "home",
    image: "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80",
    emoji: "🍳",
    price: 4200,
    oldPrice: 5400,
    rating: 4.2,
    reviewCount: 96,
    description: "Non-stick ceramic coating, induction compatible, PFOA free with tempered glass lids.",
    descriptionBn: "নন-স্টিক সিরামিক কোটিং, ইন্ডাকশন উপযোগী, PFOA মুক্ত।",
    specs: { Pieces: "5", Coating: "Ceramic non-stick", Compatible: "Gas + induction", Warranty: "1 year" },
    offers: [
      { sellerId: "s4", price: 4200, delivery: "Same day in Chattogram", stock: 9 },
      { sellerId: "s2", price: 4390, delivery: "2-3 days nationwide", stock: 30 },
    ],
    reviews: [
      { id: "r1", user: "Ruma A.", rating: 4, text: "Heats evenly, handles stay cool. Slightly heavy.", date: "2 weeks ago" },
      { id: "r2", user: "Jubayer M.", rating: 3, text: "Coating scratched within two months of daily use.", date: "1 month ago" },
    ],
    aiSummary: "Even heating and cool-touch handles are the strengths. Highly functional for everyday cooking.",
    tags: ["cookware", "kitchen", "home"],
  },
  {
    id: "p6",
    name: "Vitamin C Brightening Serum",
    nameBn: "ভিটামিন সি ব্রাইটেনিং সিরাম",
    brand: "GlowLab",
    category: "beauty",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80",
    emoji: "🧴",
    price: 1290,
    oldPrice: 1650,
    rating: 4.4,
    reviewCount: 452,
    description: "15% L-ascorbic acid with hyaluronic acid and ferulic acid, dermatologically tested.",
    descriptionBn: "১৫% এল-অ্যাসকরবিক অ্যাসিড ও হায়ালুরোনিক অ্যাসিড সমৃদ্ধ।",
    specs: { Volume: "30 ml", Actives: "15% Vit C, HA", Skin: "All types", Expiry: "18 months" },
    offers: [
      { sellerId: "s2", price: 1290, delivery: "2-3 days nationwide", stock: 200 },
      { sellerId: "s5", price: 1320, delivery: "Same day in Gulshan", stock: 45 },
      { sellerId: "s3", price: 1350, delivery: "Next day in Uttara", stock: 25 },
    ],
    reviews: [
      { id: "r1", user: "Anika T.", rating: 5, text: "Visible difference in dark spots after 6 weeks.", date: "6 days ago" },
      { id: "r2", user: "Samira N.", rating: 4, text: "Lightweight texture, absorbs fast without greasiness.", date: "2 weeks ago" },
    ],
    aiSummary: "Most users report gradual improvement in dark spots over 4-8 weeks with fast absorption.",
    tags: ["trending", "skincare", "serum", "beauty"],
  },
  {
    id: "p7",
    name: "Tape Ball Cricket Bat",
    nameBn: "টেপ বল ক্রিকেট ব্যাট",
    brand: "Rangpur Sports",
    category: "sports",
    image: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=800&q=80",
    emoji: "🏏",
    price: 1450,
    oldPrice: 1800,
    rating: 4.6,
    reviewCount: 210,
    description: "Seasoned mango wood, reinforced spine, rubberised taped grip, built for street tape-ball cricket.",
    descriptionBn: "সিজনড আমকাঠ, টেপ গ্রিপ, টেপ বল ক্রিকেটের জন্য তৈরি।",
    specs: { Wood: "Mango", Weight: "1.1 kg", Grip: "Rubber", Use: "Tape ball" },
    offers: [
      { sellerId: "s3", price: 1450, delivery: "Next day in Uttara", stock: 18 },
      { sellerId: "s1", price: 1499, delivery: "Same day in Dhanmondi", stock: 6 },
    ],
    reviews: [
      { id: "r1", user: "Sajid K.", rating: 5, text: "Great pickup for street cricket, sweet spot is wide.", date: "3 days ago" },
    ],
    aiSummary: "Reviewers agree it is well-balanced for tape-ball play with a wide sweet spot.",
    tags: ["local-artisan", "cricket", "sports", "bat"],
  },
  {
    id: "p8",
    name: "Portable Blender 400ml",
    nameBn: "পোর্টেবল ব্লেন্ডার ৪০০ মিলি",
    brand: "MixGo",
    category: "home",
    image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=800&q=80",
    emoji: "🥤",
    price: 1690,
    oldPrice: 2100,
    rating: 4.1,
    reviewCount: 134,
    description: "USB-C rechargeable, 6 stainless steel blades, BPA-free cup doubles as a travel bottle.",
    descriptionBn: "ইউএসবি-সি রিচার্জেবল, ৬ স্টেইনলেস ব্লেড, ট্রাভেল বোতল হিসেবেও ব্যবহারযোগ্য।",
    specs: { Capacity: "400 ml", Battery: "2000 mAh", Blades: "6 stainless", Charge: "USB-C" },
    offers: [
      { sellerId: "s2", price: 1690, delivery: "2-3 days nationwide", stock: 80 },
      { sellerId: "s4", price: 1740, delivery: "Same day in Chattogram", stock: 11 },
    ],
    reviews: [
      { id: "r1", user: "Priya D.", rating: 4, text: "Handles soft fruit well, perfect for office smoothies.", date: "1 week ago" },
    ],
    aiSummary: "Good for smoothies with soft fruit and protein shakes. Battery lasts roughly 12 blends per charge.",
    tags: ["budget", "kitchen", "blender", "home"],
  },
  {
    id: "p9",
    name: "RGB Mechanical Gaming Keyboard",
    nameBn: "আরজিবি মেকানিক্যাল গেমিং কীবোর্ড",
    brand: "HyperKey",
    category: "electronics",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80",
    emoji: "⌨️",
    price: 3850,
    oldPrice: 4600,
    rating: 4.7,
    reviewCount: 540,
    description: "Hot-swappable blue switches, per-key RGB backlighting, braided USB-C cable and anti-ghosting.",
    descriptionBn: "হট-সোয়াপ্যাবল ব্লু সুইচ, আরজিবি ব্যাকলাইটিং, টাইপ-সি ক্যাবল ও অ্যান্টি-ঘোস্টিং।",
    specs: { Switches: "Tactile Blue", Connection: "USB-C Detachable", Layout: "87 Keys (TKL)", RGB: "16.8M Colors" },
    offers: [
      { sellerId: "s1", price: 3850, delivery: "Same day in Dhanmondi", stock: 14 },
      { sellerId: "s3", price: 3990, delivery: "Next day in Uttara", stock: 8 },
      { sellerId: "s2", price: 3790, delivery: "2-3 days nationwide", stock: 50 },
    ],
    reviews: [
      { id: "r1", user: "Tahmid K.", rating: 5, text: "Clicky tactile feedback is super satisfying for coding and gaming.", date: "4 days ago" },
      { id: "r2", user: "Nahid R.", rating: 4, text: "Bright RGB modes. Keys are slightly loud at night.", date: "2 weeks ago" },
    ],
    aiSummary: "Praised for snappy tactile switches and durable aluminum frame. Backlight customization has extensive presets.",
    tags: ["gaming", "keyboard", "electronics", "trending"],
  },
  {
    id: "p10",
    name: "4K Ultra HD Android Smart TV Stick",
    nameBn: "৪কে আল্ট্রা এইচডি অ্যান্ড্রয়েড টিভি স্টিক",
    brand: "StreamCast",
    category: "electronics",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80",
    emoji: "📺",
    price: 4250,
    oldPrice: 5200,
    rating: 4.5,
    reviewCount: 320,
    description: "Google TV OS, Dolby Vision & Atmos, Quad-core processor with voice remote and Chromecast built-in.",
    descriptionBn: "গুগল টিভি ওএস, ডলবি ভিশন ও অ্যাটমোস, ভয়েস রিমোট এবং বিল্ট-ইন ক্রোমকাস্ট।",
    specs: { Resolution: "4K 60fps", RAM: "2GB", Storage: "16GB", Connectivity: "Wi-Fi 5GHz, BT 5.0" },
    offers: [
      { sellerId: "s1", price: 4250, delivery: "Same day in Dhanmondi", stock: 10 },
      { sellerId: "s2", price: 4199, delivery: "2-3 days nationwide", stock: 35 },
    ],
    reviews: [
      { id: "r1", user: "Zubair M.", rating: 5, text: "Turned my old LED TV into a snappy smart TV. Netflix 4K runs smoothly.", date: "1 week ago" },
    ],
    aiSummary: "Effortless streaming setup with fast UI response and reliable 5GHz Wi-Fi reception.",
    tags: ["streaming", "tv", "electronics", "popular"],
  },
  {
    id: "p11",
    name: "Waterproof Portable Bluetooth Speaker",
    nameBn: "ওয়াটারপ্রুফ পোর্টেবল ব্লুটুথ স্পিকার",
    brand: "BassBlast",
    category: "electronics",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80",
    emoji: "🔊",
    price: 2150,
    oldPrice: 2800,
    rating: 4.6,
    reviewCount: 410,
    description: "IPX7 waterproof rating, 360-degree stereo sound, 16h playtime with deep punchy bass.",
    descriptionBn: "আইপিএক্স৭ ওয়াটারপ্রুফ, ৩৬০ ডিগ্রি স্টেরিও সাউন্ড এবং ১৬ ঘণ্টা প্লেব্যাক।",
    specs: { Battery: "16 hours", Output: "20W RMS", Waterproof: "IPX7", Bluetooth: "5.2" },
    offers: [
      { sellerId: "s3", price: 2150, delivery: "Next day in Uttara", stock: 22 },
      { sellerId: "s1", price: 2200, delivery: "Same day in Dhanmondi", stock: 9 },
    ],
    reviews: [
      { id: "r1", user: "Kazi S.", rating: 5, text: "Incredible bass for its size. Survived rain during a rooftop party.", date: "3 days ago" },
    ],
    aiSummary: "Strong audio clarity, punchy bass, and solid rugged waterproofing make it a customer favourite for travel.",
    tags: ["speaker", "audio", "bluetooth", "trending"],
  },
  {
    id: "p12",
    name: "Fast Charging 20000mAh Power Bank 65W",
    nameBn: "ফাস্ট চার্জিং ২০০০০ এমএএইচ পাওয়ার ব্যাংক ৬৫ ওয়াট",
    brand: "PowerCore",
    category: "electronics",
    image: "https://images.unsplash.com/photo-1609592424364-c2c8fcf4f54d?auto=format&fit=crop&w=800&q=80",
    emoji: "🔋",
    price: 2650,
    oldPrice: 3200,
    rating: 4.8,
    reviewCount: 680,
    description: "65W Power Delivery can charge laptops, tablets and smartphones simultaneously. LED digital display.",
    descriptionBn: "৬৫ ওয়াট পাওয়ার ডেলিভারি, ল্যাপটপ ও ফোন দ্রুত চার্জ করার উপযোগী ডিজিটাল ডিসপ্লেসহ।",
    specs: { Capacity: "20,000 mAh", MaxOutput: "65W PD", Ports: "2x USB-C, 1x USB-A", Display: "LED Percentage" },
    offers: [
      { sellerId: "s1", price: 2650, delivery: "Same day in Dhanmondi", stock: 18 },
      { sellerId: "s2", price: 2590, delivery: "2-3 days nationwide", stock: 65 },
    ],
    reviews: [
      { id: "r1", user: "Arif H.", rating: 5, text: "Charges my MacBook Air and iPhone rapidly during load-shedding.", date: "5 days ago" },
    ],
    aiSummary: "Highly recommended for charging laptops and phones. Accurate LED percentage display is very useful.",
    tags: ["powerbank", "travel", "budget", "electronics"],
  },
  {
    id: "p13",
    name: "Pure Cold-Pressed Mustard Oil 1L",
    nameBn: "খাঁটি ঘানি ভাঙা সরিষার তেল ১ লিটার",
    brand: "Shuddho",
    category: "grocery",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80",
    emoji: "🫒",
    price: 340,
    oldPrice: 380,
    rating: 4.9,
    reviewCount: 512,
    description: "100% traditional wooden ghani pressed mustard oil, raw pungency and rich natural aroma.",
    descriptionBn: "কাঠের ঘানিতে ভাঙা ১০০% খাঁটি ঝাঁঝালো সরিষার তেল।",
    specs: { Volume: "1 Litre", Process: "Cold-pressed Wood Ghani", Purity: "100% Raw", Origin: "Pabna" },
    offers: [
      { sellerId: "s6", price: 340, delivery: "Same day in Mirpur", stock: 50 },
      { sellerId: "s4", price: 350, delivery: "Same day in Chattogram", stock: 30 },
      { sellerId: "s1", price: 360, delivery: "Same day in Dhanmondi", stock: 25 },
    ],
    reviews: [
      { id: "r1", user: "Morshed A.", rating: 5, text: "Authentic strong jhajh (pungency), perfect for bhorta and pickles.", date: "2 days ago" },
    ],
    aiSummary: "Customers love the authentic strong pungency and unadulterated smell for traditional Bengali cooking.",
    tags: ["organic", "oil", "local-favourite", "grocery"],
  },
  {
    id: "p14",
    name: "Sundarban Wild Raw Organic Honey 500g",
    nameBn: "সুন্দরবনের প্রাকৃতিক মধু ৫০০ গ্রাম",
    brand: "Sundarban Forest",
    category: "grocery",
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80",
    emoji: "🍯",
    price: 680,
    oldPrice: 790,
    rating: 4.8,
    reviewCount: 389,
    description: "Collected directly by traditional mouwals from wild Khalisa flowers in the Sundarban mangrove.",
    descriptionBn: "সুন্দরবনের খলিশা ফুলের প্রাকৃতিক চাক ভাঙা খাঁটি মধু।",
    specs: { Weight: "500 g", Type: "Wild Khalisa Flower", Processing: "Unfiltered Raw", Origin: "Sundarbans" },
    offers: [
      { sellerId: "s6", price: 680, delivery: "Same day in Mirpur", stock: 28 },
      { sellerId: "s4", price: 695, delivery: "Same day in Chattogram", stock: 15 },
    ],
    reviews: [
      { id: "r1", user: "Lamia R.", rating: 5, text: "Rich distinct floral flavor. Not overly sweet like processed honey.", date: "1 week ago" },
    ],
    aiSummary: "Praised for genuine floral aroma and raw unprocessed taste with natural enzymes intact.",
    tags: ["organic", "honey", "local-artisan", "grocery"],
  },
  {
    id: "p15",
    name: "Premium Sylhet Garden Black & Green Tea 400g",
    nameBn: "শ্রীমঙ্গল প্রিমিয়াম ব্ল্যাক ও গ্রিন টি ৪০০ গ্রাম",
    brand: "Sylhet Hills",
    category: "grocery",
    image: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=800&q=80",
    emoji: "🍵",
    price: 420,
    oldPrice: 490,
    rating: 4.7,
    reviewCount: 275,
    description: "Hand-picked CTC first flush tea leaves from Sreemangal tea estates. Rich amber liquor and brisk taste.",
    descriptionBn: "শ্রীমঙ্গলের পাহাড়ি চা বাগান থেকে সংগৃহীত ফার্স্ট ফ্লাশ চা পাতা।",
    specs: { Weight: "400 g", Grade: "BOP CTC", Harvest: "First Flush", Origin: "Sreemangal, Sylhet" },
    offers: [
      { sellerId: "s6", price: 420, delivery: "Same day in Mirpur", stock: 40 },
      { sellerId: "s1", price: 435, delivery: "Same day in Dhanmondi", stock: 18 },
    ],
    reviews: [
      { id: "r1", user: "Enamul C.", rating: 5, text: "Strong aroma and bright liquor. Best morning tea.", date: "3 days ago" },
    ],
    aiSummary: "Recognised for rich color, full-bodied taste, and pleasant fresh aroma.",
    tags: ["beverage", "tea", "local-favourite", "grocery"],
  },
  {
    id: "p16",
    name: "Fresh Rajshahi Himsagar Mangoes 5kg Crate",
    nameBn: "রাজশাহীর মিষ্টি হিমসাগর আম ৫ কেজি",
    brand: "Rajshahi Orchards",
    category: "grocery",
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=800&q=80",
    emoji: "🥭",
    price: 1250,
    oldPrice: 1500,
    rating: 4.9,
    reviewCount: 820,
    description: "Naturally ripened chemical-free Himsagar mangoes directly from Chapainawabganj orchards.",
    descriptionBn: "গাছপাকা ফরমালিনমুক্ত মিষ্টি হিমসাগর আম সরাসরি বাগান থেকে।",
    specs: { Weight: "5 kg crate", Variety: "Himsagar", Ripening: "100% Chemical-free", Origin: "Rajshahi" },
    offers: [
      { sellerId: "s6", price: 1250, delivery: "Same day in Mirpur", stock: 30 },
      { sellerId: "s4", price: 1290, delivery: "Same day in Chattogram", stock: 20 },
      { sellerId: "s1", price: 1320, delivery: "Same day in Dhanmondi", stock: 15 },
    ],
    reviews: [
      { id: "r1", user: "Naznin F.", rating: 5, text: "Extremely sweet, thin skin and no fiber. Freshly picked!", date: "Yesterday" },
    ],
    aiSummary: "Top rated for exceptional sweetness, thin seed, fiberless pulp, and damage-free protective packaging.",
    tags: ["fruit", "mango", "seasonal", "trending"],
  },
  {
    id: "p17",
    name: "Traditional Handwoven Jamdani Silk Saree",
    nameBn: "ঐতিহ্যবাহী হাতে বোনা জামদানি সিল্ক শাড়ি",
    brand: "Narayanganj Heritage",
    category: "fashion",
    image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80",
    emoji: "🥻",
    price: 6500,
    oldPrice: 8500,
    rating: 4.9,
    reviewCount: 240,
    description: "Authentic 84-count fine cotton silk Jamdani with intricate floral motifs crafted by master weavers.",
    descriptionBn: "নারায়ণগঞ্জের তাঁতিদের হাতে বোনা সুক্ষ্ম নকশার রাজকীয় জামদানি শাড়ি।",
    specs: { Count: "84 count", Material: "Cotton Silk Blend", Length: "12 hands (with blouse piece)", Origin: "Rupganj" },
    offers: [
      { sellerId: "s5", price: 6500, delivery: "Same day in Gulshan", stock: 8 },
      { sellerId: "s2", price: 6750, delivery: "2-3 days nationwide", stock: 15 },
    ],
    reviews: [
      { id: "r1", user: "Sadia M.", rating: 5, text: "Workmanship is breathtaking. Soft drape and very lightweight.", date: "4 days ago" },
    ],
    aiSummary: "Exquisite craftsmanship and soft handloom feel. Highly appreciated for wedding and festive wear.",
    tags: ["local-artisan", "saree", "jamdani", "fashion", "festive"],
  },
  {
    id: "p18",
    name: "Classic Washed Vintage Denim Jacket",
    nameBn: "ক্লাসিক ওয়াশড ভিন্টেজ ডেনিম জ্যাকেট",
    brand: "UrbanThread",
    category: "fashion",
    image: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80",
    emoji: "🧥",
    price: 2450,
    oldPrice: 3200,
    rating: 4.5,
    reviewCount: 190,
    description: "Heavyweight 13oz cotton denim with button flap chest pockets and adjustable waist tabs.",
    descriptionBn: "প্রিমিয়াম কোয়ালিটি কটন ডেনিম জ্যাকেট, স্টাইলিশ ও আরামদায়ক ফিটিং।",
    specs: { Material: "100% Cotton Denim (13oz)", Closure: "Metal Button", Fit: "Relaxed Vintage", Sizes: "M-XXL" },
    offers: [
      { sellerId: "s5", price: 2450, delivery: "Same day in Gulshan", stock: 16 },
      { sellerId: "s2", price: 2490, delivery: "2-3 days nationwide", stock: 45 },
    ],
    reviews: [
      { id: "r1", user: "Shahriar T.", rating: 5, text: "Great sturdy fabric and the wash looks premium in person.", date: "1 week ago" },
    ],
    aiSummary: "Praised for rugged denim quality and modern casual fit.",
    tags: ["jacket", "denim", "trending", "fashion", "casual"],
  },
  {
    id: "p19",
    name: "Genuine Leather Bi-Fold Wallet & Belt Set",
    nameBn: "খাঁটি চামড়ার মানিব্যাগ ও বেল্ট গিফট সেট",
    brand: "Bengal Tannery",
    category: "fashion",
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80",
    emoji: "👛",
    price: 1850,
    oldPrice: 2400,
    rating: 4.6,
    reviewCount: 310,
    description: "Top-grain cowhide leather with RFID blocking wallet and reversible brass buckle belt.",
    descriptionBn: "টপ-গ্রেইন লেদার দিয়ে তৈরি আরএফআইডি মানিব্যাগ ও প্রিমিয়াম বেল্ট সেট।",
    specs: { Leather: "Top-grain Cowhide", RFID: "Protected", BeltLength: "32-44 inch adjustable", Box: "Luxury Gift Box" },
    offers: [
      { sellerId: "s5", price: 1850, delivery: "Same day in Gulshan", stock: 24 },
      { sellerId: "s1", price: 1890, delivery: "Same day in Dhanmondi", stock: 12 },
    ],
    reviews: [
      { id: "r1", user: "Fahim E.", rating: 5, text: "Leather smells authentic and feels durable. Made a great birthday gift.", date: "2 weeks ago" },
    ],
    aiSummary: "Sturdy build, genuine leather texture, and luxury packaging make it ideal for gifting.",
    tags: ["leather", "wallet", "belt", "fashion", "gift"],
  },
  {
    id: "p20",
    name: "Ultrasonic Wooden Essential Oil Diffuser",
    nameBn: "আল্ট্রাসনিক উডেন এসেনশিয়াল অয়েল ডিফিউজার",
    brand: "AromaBreeze",
    category: "home",
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=80",
    emoji: "🌿",
    price: 1950,
    oldPrice: 2500,
    rating: 4.7,
    reviewCount: 175,
    description: "Whisper-quiet ultrasonic mist, 7-color soothing LED lights and auto shut-off waterless protection.",
    descriptionBn: "শান্ত আল্ট্রাসনিক মিস্ট, ৭ রঙের এলইডি আলো এবং অটো শাট-অফ সুবিধা।",
    specs: { Capacity: "500 ml", Timer: "1h/3h/6h/Continuous", Light: "7 LED Modes", Coverage: "Up to 300 sq ft" },
    offers: [
      { sellerId: "s5", price: 1950, delivery: "Same day in Gulshan", stock: 14 },
      { sellerId: "s2", price: 1999, delivery: "2-3 days nationwide", stock: 35 },
    ],
    reviews: [
      { id: "r1", user: "Maliha K.", rating: 5, text: "Makes my bedroom smell like a spa. Very quiet operation.", date: "5 days ago" },
    ],
    aiSummary: "Users love the natural wood finish and tranquil atmospheric misting for bedrooms or offices.",
    tags: ["diffuser", "wellness", "home-decor", "home"],
  },
  {
    id: "p21",
    name: "Eye-Care LED Touch Desk Lamp with USB",
    nameBn: "আই-কেয়ার টাচ এলইডি ডেস্ক ল্যাম্প",
    brand: "Lumina",
    category: "home",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80",
    emoji: "💡",
    price: 1550,
    oldPrice: 1950,
    rating: 4.6,
    reviewCount: 220,
    description: "Flicker-free eye protection, 5 color temperatures, step-less touch dimming and flexible gooseneck arm.",
    descriptionBn: "ফ্লিকার-ফ্রি চোখ সুরক্ষাকারী এলইডি, ৫টি কালার টেম্পারেচার ও টাচ কন্ট্রোল।",
    specs: { Power: "12W LED", Brightness: "800 Lumens", ColorTemp: "2700K - 6500K", USBPort: "5V/1A output" },
    offers: [
      { sellerId: "s1", price: 1550, delivery: "Same day in Dhanmondi", stock: 20 },
      { sellerId: "s3", price: 1590, delivery: "Next day in Uttara", stock: 15 },
    ],
    reviews: [
      { id: "r1", user: "Hasan U.", rating: 5, text: "Warm yellow light is very comfortable for late-night reading.", date: "1 week ago" },
    ],
    aiSummary: "Excellent eye-friendly lighting controls with helpful built-in USB charging port.",
    tags: ["lamp", "study", "lighting", "home"],
  },
  {
    id: "p22",
    name: "Herbal Onion & Bhringraj Hair Growth Oil 200ml",
    nameBn: "ভেষজ পেঁয়াজ ও ভৃঙ্গরাজ হেয়ার অয়েল ২০০ মিলি",
    brand: "AyurVeda Natural",
    category: "beauty",
    image: "https://images.unsplash.com/photo-1608248597359-598d98d28cf4?auto=format&fit=crop&w=800&q=80",
    emoji: "🌿",
    price: 550,
    oldPrice: 680,
    rating: 4.6,
    reviewCount: 415,
    description: "Formulated with red onion extract, bhringraj, amla and black seed oil to reduce hair fall and promote growth.",
    descriptionBn: "লাল পেঁয়াজের নির্যাস, ভৃঙ্গরাজ ও কালোজিরার তেল সমৃদ্ধ প্রাকৃতিক হেয়ার অয়েল।",
    specs: { Volume: "200 ml", Ingredients: "Red Onion, Bhringraj, Amla, Kalonji", FreeFrom: "Mineral Oil, Parabens" },
    offers: [
      { sellerId: "s5", price: 550, delivery: "Same day in Gulshan", stock: 35 },
      { sellerId: "s6", price: 560, delivery: "Same day in Mirpur", stock: 40 },
    ],
    reviews: [
      { id: "r1", user: "Tania P.", rating: 5, text: "Hair fall reduced noticeably in 3 weeks. Pleasant non-sticky scent.", date: "6 days ago" },
    ],
    aiSummary: "Effective herbal formulation for controlling hair fall and improving scalp health without harsh chemicals.",
    tags: ["haircare", "organic", "oil", "beauty"],
  },
  {
    id: "p23",
    name: "Long-Lasting Matte Liquid Lipstick Set",
    nameBn: "লং-লাস্টিং ম্যাট লিকুইড লিপস্টিক সেট",
    brand: "VelvetTouch",
    category: "beauty",
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80",
    emoji: "💄",
    price: 890,
    oldPrice: 1200,
    rating: 4.5,
    reviewCount: 360,
    description: "Set of 4 nude and berry shades, transfer-proof 12-hour wear infused with hydrating vitamin E.",
    descriptionBn: "১২ ঘণ্টা স্থায়ী ওয়াটারপ্রুফ ম্যাট ফিনিশ লিপস্টিক সেট ভিটামিন ই সমৃদ্ধ।",
    specs: { Count: "4 shades (5ml each)", Finish: "Velvet Matte", Duration: "12 Hours", Hydration: "Vitamin E" },
    offers: [
      { sellerId: "s5", price: 890, delivery: "Same day in Gulshan", stock: 50 },
      { sellerId: "s2", price: 920, delivery: "2-3 days nationwide", stock: 100 },
    ],
    reviews: [
      { id: "r1", user: "Rima S.", rating: 5, text: "Super pigmented and comfortable on the lips. Doesn't dry them out.", date: "1 week ago" },
    ],
    aiSummary: "Praised for smooth glide, vibrant pigmentation, and non-drying matte texture.",
    tags: ["makeup", "lipstick", "beauty", "trending"],
  },
  {
    id: "p24",
    name: "Dual Badminton Rackets with Nylon Shuttles",
    nameBn: "ডুয়াল ব্যাডমিন্টন র‍্যাকেট ও কর্ক সেট",
    brand: "Victor Pro",
    category: "sports",
    image: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=800&q=80",
    emoji: "🏸",
    price: 2350,
    oldPrice: 3100,
    rating: 4.7,
    reviewCount: 290,
    description: "Lightweight carbon fiber frame with high-tension strings, foam grips and 3 durable nylon shuttles.",
    descriptionBn: "কার্বন ফাইবার ফ্রেমের হালকা ও শক্তিশালী জোড়া র‍্যাকেট এবং কর্ক সেট।",
    specs: { Material: "Carbon Aluminum Composite", Tension: "24-26 lbs", Weight: "85g per racket", Includes: "2 Rackets + 3 Shuttles + Cover" },
    offers: [
      { sellerId: "s3", price: 2350, delivery: "Next day in Uttara", stock: 16 },
      { sellerId: "s1", price: 2390, delivery: "Same day in Dhanmondi", stock: 10 },
    ],
    reviews: [
      { id: "r1", user: "Rashed N.", rating: 5, text: "Very light in the hand with powerful smash control. Great value.", date: "4 days ago" },
    ],
    aiSummary: "Lightweight, responsive, and ideal for recreational and club badminton players.",
    tags: ["badminton", "sports", "outdoor", "popular"],
  },
  {
    id: "p25",
    name: "Anti-Slip Eco-Friendly 6mm Yoga Mat",
    nameBn: "অ্যান্টি-স্লিপ ইকো ফ্রেন্ডলি ৬মিমি ইয়োগা ম্যাট",
    brand: "FlexFit",
    category: "sports",
    image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=800&q=80",
    emoji: "🧘",
    price: 1150,
    oldPrice: 1500,
    rating: 4.8,
    reviewCount: 340,
    description: "High-density dual-layer TPE cushioning, textured grip surface with carry strap for floor workouts and yoga.",
    descriptionBn: "উচ্চ ঘনত্বের টিপিই ফোমযুক্ত অ্যান্টি-স্লিপ ব্যায়াম ও ইয়োগা ম্যাট।",
    specs: { Thickness: "6 mm", Dimensions: "183 cm x 61 cm", Material: "Non-toxic Eco TPE", Includes: "Free Carry Strap" },
    offers: [
      { sellerId: "s3", price: 1150, delivery: "Next day in Uttara", stock: 25 },
      { sellerId: "s5", price: 1190, delivery: "Same day in Gulshan", stock: 15 },
    ],
    reviews: [
      { id: "r1", user: "Zinath B.", rating: 5, text: "Excellent knee support during Pilates and doesn't slip on tiles.", date: "1 week ago" },
    ],
    aiSummary: "Top rated for comfortable 6mm joint cushioning, odorless eco-friendly material, and non-slip floor grip.",
    tags: ["yoga", "fitness", "exercise", "sports", "budget"],
  },
];

export const coupons = [
  { code: "LOCAL100", label: "৳100 off on local seller orders", cost: 500, expires: "31 Aug" },
  { code: "FRESH15", label: "15% off grocery, max ৳200", cost: 800, expires: "20 Aug" },
  { code: "FREESHIP", label: "Free delivery on any order", cost: 300, expires: "15 Sep" },
  { code: "SUMMER500", label: "৳500 off on orders over ৳3000", cost: 1000, expires: "30 Sep" },
];

export const notificationsSeed = [
  { id: "n1", type: "order", title: "Order #HL-2291 is out for delivery", titleBn: "অর্ডার #HL-2291 ডেলিভারির পথে", time: "12 min ago" },
  { id: "n2", type: "price", title: "Price drop: Headphones now ৳6,299", titleBn: "দাম কমেছে: হেডফোন এখন ৳৬,২৯৯", time: "1 hr ago" },
  { id: "n3", type: "promo", title: "Flash sale in Dhanmondi ends in 2 hours", titleBn: "ধানমন্ডিতে ফ্ল্যাশ সেল ২ ঘণ্টায় শেষ", time: "3 hr ago" },
  { id: "n4", type: "reward", title: "You earned 120 coins from your last order", titleBn: "শেষ অর্ডারে ১২০ কয়েন পেয়েছেন", time: "Yesterday" },
];

export const orderSeed = [
  {
    id: "HL-2291",
    date: "29 Jul 2026",
    items: [{ productId: "p1", qty: 1 }],
    total: 6450,
    payment: "bKash",
    status: 2,
    seller: "s1",
  },
  {
    id: "HL-2264",
    date: "22 Jul 2026",
    items: [{ productId: "p3", qty: 2 }, { productId: "p8", qty: 1 }],
    total: 3520,
    payment: "Cash on Delivery",
    status: 3,
    seller: "s4",
  },
];

export const trackingSteps = [
  { key: "confirmed", en: "Order confirmed", bn: "অর্ডার নিশ্চিত" },
  { key: "packed", en: "Packed by seller", bn: "বিক্রেতা প্যাক করেছেন" },
  { key: "transit", en: "Out for delivery", bn: "ডেলিভারির পথে" },
  { key: "delivered", en: "Delivered", bn: "ডেলিভারি সম্পন্ন" },
];
